### ISSUE TITLE
Bluetooth person tracker project MVP

### ISSUE THREAD

**Issue by neopunisher** [Liberty-IT/.github#5]
We need a way to use hardware to scan nearby devices and then aggregate it 

- [x] We need to identify some hardware that has bluetooth and can collect messages
- [x] How are we going to store it?
- [x] What are we going to store? distance strength format
- [ ] How do we detect volunteers devices? 
- [ ] How do we distinguish a visitor?
- [ ] Get prototype hardware (raspberry pi) 
- [ ] Collect test data for analysis 
- [x] Decoder to generate text version
- [x] Converter for wireshark captures to bin

**Comment by neopunisher** [comment]
https://raspberrypi.stackexchange.com/questions/104304/is-it-possible-to-log-any-discoverable-bluetooth-ble-via-headless-pi

**Comment by neopunisher** [comment]
## Binary Format Structure

1. **Bluetooth MAC Address (6 bytes):**
   - A Bluetooth MAC address is 48 bits long, stored as 6 bytes.

2. **RSSI (1 byte):**
   - RSSI values are represented as signed 8-bit integers, allowing values from -128 to 127.

3. **Timestamp (4 bytes):**
   - Use a Unix timestamp, a 32-bit unsigned integer, valid until the year 2038.

### Total Size

- **Total:** 11 bytes per record.

**Comment by kfeaginsiii** [comment]
Bluefruit Sniffer
https://www.adafruit.com/product/2269

**Comment by neopunisher** [comment]
Here is some other peoples implementations:
https://www.manxtechgroup.com/people-counting-using-wifi-and-bluetooth/
https://www.peoplecounters.com/index.php?cu=us


Adafruit Tutorials for Hardware:
https://learn.adafruit.com/bluefruit-le-connect
https://www.adafruit.com/product/2267
https://learn.adafruit.com/reverse-engineering-a-bluetooth-low-energy-light-bulb/explore-gatt
https://learn.adafruit.com/introduction-to-bluetooth-low-energy/introduction
https://docs.nordicsemi.com/bundle/nrfutil/page/nrfutil-ble-sniffer/guides/overview.html

Bt apps:
https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en

**Comment by neopunisher** [comment]
![image](https://github.com/user-attachments/assets/15795fa6-59a7-4027-a39b-c896c9ed542b)

**Comment by neopunisher** [comment]
![image](https://github.com/user-attachments/assets/6f03ce3e-0f97-4b94-9038-44e5dd75a874)
![image](https://github.com/user-attachments/assets/6806117e-c2d8-46f3-925c-2e34aaaf306a)
![image](https://github.com/user-attachments/assets/3e5f1975-0174-48ed-bd18-cccd16c51911)
![image](https://github.com/user-attachments/assets/274cbb33-0845-4c3b-9169-58085fe7ce48)
![image](https://github.com/user-attachments/assets/6f9332e8-9050-479c-b301-6bf2242f50ea)
